version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle.kts" }}
            - v2-dependencies-
      - run:
          name: Build
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle.kts" }}
  test:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle.kts" }}
            - v2-dependencies-
      - run:
          name: Test
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle.kts" }}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build