version: 2.1

executors:
  builder:
    docker:
      - image: cimg/openjdk:17.0.3
    resource_class: medium+

commands:
  install_dependencies:
    steps:
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle.kts" }}
            - v2-dependencies-
      - run:
          name: Download dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle.kts" }}

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Build
          command: ./gradlew build
  test:
    executor: builder
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Test
          command: ./gradlew test
  deploy:
    executor: builder
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "Deploy main branch to the remote!!!"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main